#!/bin/bash
#
#SBATCH --job-name=geogrid
#SBATCH --output=geogrid_out.txt
#SBATCH --ntasks-per-node=1
#SBATCH --nodes=1
#SBATCH --time=15:00
#SBATCH -p short-40core-shared
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=joshua.carter@stonybrook.edu

module load intel/compiler/64/2020/20.0.2
module load intel/mkl/64/2020/20.0.2
module load intel/mpi/64/2020/20.0.2

#should be in /WRF
bw_dir="/gpfs/home/jjcarter/MILAN_WRF/Build_WRF" #the location where Build_WRF is found (and built)

#not convinced the following is needed, but what have we got to lose?
export LD_LIBRARY_PATH="$bw_dir/wrf_libs_intel/lib:$LD_LIBRARY_PATH"
export LDFLAGS="-L/$bw_dir/wrf_libs_intel/lib"
export CPPFLAGS="-I/$bw_dir/wrf_libs_intel/include"

export CC=icc
export FC=ifort
export F90=ifort
export CXX=icpc
export NETCDF=$bw_dir/wrf_libs_intel/
export HDF5=$bw_dir/wrf_libs_intel/

#the following may be needed if recompiling WPS (not needed for registry change)
export WRF_DIR=/gpfs/home/jjcarter/MILAN_WRF/Build_WRF/WRF/
export JASPERLIB=$bw_dir/wrf_libs_intel/lib/
export JASPERINC=$bw_dir/wrf_libs_intel/include/

#ulimit -s 262140
ulimit -s unlimited
./geogrid.exe
